baseURL: https://naiarasandi1995.github.io/NaiaraWebsite/
publishDIR: docs
languageCode: en-US
title: Naiara Alcantara
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Naiara Sandi de A. Alcantara
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Describe
  social:
    Email: nayara_sandy@hotmail.com
    Github: https://github.com/NaiaraSandi1995
    LinkedIn: https://www.linkedin.com/in/naiarasandi/
    Lattes: http://lattes.cnpq.br/3451135311500060
    Twitter: https://twitter.com/NaiaraSandi
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 100
    - identifier: projetos
      name: projetos
      url: /projetos/
      weight: 200
    - identifier: resumo
      name: resumo
      url: /resumo/
      weight: 300
