baseURL: https://naiarasandi1995.github.io/NaiaraWebsite/
publishDIR: docs
languageCode: en-US
title: Naiara Alcantara
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Naiara Sandi de A. Alcantara
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Describe
  social:
    Email: email@example.com
    Github: userll
    LinkedIn: username
    Medium: username
    RSS: /blog/index.xml
    Stackoverflow: username
    Telegram: username
    Twitter: username
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resumo
      name: resumo
      url: /resume/
      weight: 300
