baseURL: https://naiarasandi1995.github.io/NaiaraWebsite/
publishDIR: docs
languageCode: en-US
title: Naiara Alcantara
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Naiara Alcantara
  avatar: img/profile.jpg
  custom_css: []
  custom_js: []
  description: Describe your website
  social:
    Email: nayara_sandy@hotmail.com
    Github: https://github.com/NaiaraSandi1995
    LinkedIn: https://www.linkedin.com/in/naiarasandi/
    Twitter: https://twitter.com/NaiaraSandi
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 100


